"""Runtime command descriptors implemented by the interactive harness."""

RUNTIME_COMMAND_SPECS = {
    "add-dir": {"help_text": "Add a workspace directory to the active session"},
    "advisor": {"help_text": "Run an advisor review over session and git context"},
    "agents": {"help_text": "List, inspect, create, and manage local agents"},
    "brief": {"help_text": "Toggle brief-only assistant responses"},
    "btw": {"help_text": "Ask a quick side question using session context"},
    "buddy": {"help_text": "Manage the local buddy companion state"},
    "color": {"help_text": "Set the current session color"},
    "commit": {"help_text": "Inspect git commit readiness"},
    "commit-push-pr": {"help_text": "Inspect branch, diff, and PR publish readiness"},
    "ctx_viz": {"help_text": "Render loaded context and recent transcript details"},
    "feedback": {"help_text": "Capture feedback with repository context"},
    "fork": {"help_text": "Launch or resume a background subagent"},
    "hooks": {"help_text": "List configured runtime hooks"},
    "init": {"help_text": "Generate an AGENTS.md project guide"},
    "insights": {"help_text": "Show current session analytics"},
    "magic-docs": {"help_text": "Inspect or refresh tracked Magic Docs"},
    "managed-settings": {"help_text": "Inspect managed runtime policy settings"},
    "onboarding": {"help_text": "Show local setup checklist status"},
    "peers": {"help_text": "Create and manage local agent teams"},
    "plan": {"help_text": "Enter read-only plan mode"},
    "pr-comments": {"help_text": "Render GitHub PR comments for the current branch"},
    "pr_comments": {"help_text": "Render GitHub PR comments for the current branch"},
    "privacy-settings": {"help_text": "Show local privacy and data-storage settings"},
    "release-notes": {"help_text": "Show recent Koder release notes or commits"},
    "sandbox": {"help_text": "Inspect and configure sandbox settings"},
    "schedule": {"help_text": "Inspect scheduled task registry"},
    "security-review": {"help_text": "Run a security-focused review of pending changes"},
    "share": {"help_text": "Show share metadata for the active session"},
    "statusline": {"help_text": "Configure or clear the terminal status line"},
    "subscribe-pr": {"help_text": "Inspect open PRs and subscription guidance"},
    "teleport": {"help_text": "Change the active workspace directory"},
    "terminal-setup": {"help_text": "Inspect terminal environment settings"},
    "terminalSetup": {"help_text": "Inspect terminal environment settings"},
    "torch": {"help_text": "Explore a codebase topic with a structured plan"},
    "ultraplan": {"help_text": "Create a comprehensive implementation plan"},
    "vim": {"help_text": "Toggle vim input mode"},
    "voice": {"help_text": "Configure or toggle provider-backed voice mode"},
}
